---
title: "Reproducible Research: Peer Assessment 1"
author: "Roger K. Winters"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r}
activity_data <- read.csv("activity.csv")
```

## What is mean total number of steps taken per day?

```{r}
steps_per_day <- aggregate(steps ~ date, activity_data, sum)

hist(steps_per_day$steps, breaks = 8, 
     main = paste("Total Number of Steps Taken Each Day"), 
     xlab = "Number of Steps", 
     ylab = "Frequency")

mean(steps_per_day$steps)
median(steps_per_day$steps)
```

## What is the average daily activity pattern?

```{r}
avg_daily_pattern <- aggregate(steps ~ interval, activity_data, mean)

plot(avg_daily_pattern$interval, avg_daily_pattern$steps, type = "l", xlab = "5-min Intervals", 
        ylab = "Average Number of Steps Taken Across All Days", main = "Average Daily Activity Pattern")

avg_daily_pattern[which.max(avg_daily_pattern$steps),]
```

## Imputing missing values

```{r}
library(Hmisc)

sum(is.na(activity_data$steps))

activity_data_imputed <- activity_data
activity_data_imputed$steps <- as.integer(with(activity_data_imputed, round(impute(steps, mean))))
steps_per_day_imputed <- aggregate(steps ~ date, activity_data_imputed, sum)
mean(steps_per_day_imputed$steps)
median(steps_per_day_imputed$steps)

hist(steps_per_day_imputed$steps, breaks = 8, 
     main = paste("Total Number of Steps Taken Each Day (Imputed)"), 
     xlab = "Number of Steps", 
     ylab = "Frequency")

```

## Are there differences in activity patterns between weekdays and weekends?
